all:
#	clear
	g++ -g -std=c++0x trend_detection.cpp signalSource.cpp signal.cpp mytools.cpp nikolov.cpp params.cpp set_util.cpp approach_1.cpp approach_2.cpp mm.cpp simulator.cpp -o trend

trendma:
	g++ -g -std=c++0x trend_ma.cpp mytools.cpp  mm.cpp simulator.cpp  -o trendMA
