#!/bin/bash

#ordem dos parametros
# gama theta detectionsLimit NSMOOTH NREF NOBS NTREND NTRESH

#tipos dos parametros
# gama float
# theta float
# detectionsLimit int
# NSMOOTH int
# NREF int
# NOBS int
# NTREND int
# NTRESH float

# linhas de teste
gama=1
theta=1
detLim=3
nSmooth=10
nRef=30
nObs=5
nTrend=15
nTresh=0.1


# alterar a quantidade de repeticoes conforme necessario
for i in {1..1000}
do
	./trend $gama $theta $detLim $nSmooth $nRef $nObs $nTrend $nTresh
done





